# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20170405_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_friends_+', to='bbs.UserProfile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(upload_to='uploads', verbose_name='文章标题图片'),
        ),
        migrations.AlterField(
            model_name='category',
            name='admin',
            field=models.ManyToManyField(blank=True, to='bbs.UserProfile'),
        ),
    ]
